# Generated by Django 3.1.4 on 2020-12-03 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clubuser',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='clubuser',
            name='interest',
        ),
        migrations.AddField(
            model_name='clubuser',
            name='interest',
            field=models.ManyToManyField(to='blog.Category'),
        ),
        migrations.AlterField(
            model_name='clubuser',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
