# Generated by Django 3.1.4 on 2020-12-29 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubuser', '__first__'),
        ('blog', '0004_answer_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='user_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='clubuser.clubuser'),
        ),
    ]
