# Generated by Django 3.1.4 on 2020-12-26 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_question_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='views',
        ),
    ]
