# Generated by Django 3.1.4 on 2020-12-29 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20201229_1636'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='total_like',
        ),
    ]
