# Generated by Django 3.1.4 on 2020-12-27 14:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0006_remove_question_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='like',
            field=models.ManyToManyField(related_name='like_question', to=settings.AUTH_USER_MODEL),
        ),
    ]
