# Generated by Django 3.1.4 on 2020-12-03 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20201203_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='published',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='clubuser',
            name='gender',
            field=models.CharField(choices=[('male', 'آقا'), ('woman', 'خانم')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='like_number',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
