# Generated by Django 3.1.4 on 2020-12-30 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20201230_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='reason',
            field=models.CharField(choices=[('not related to programing', 'not related to programing'), ('insulting', 'insulting'), ('sexual matters', 'sexual matters'), ('wrong answer', 'wrong answer'), ('inappropriate', 'inappropriate'), ('other', 'other')], default='publish', max_length=35),
        ),
    ]
