# Generated by Django 3.1.4 on 2020-12-30 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20201230_0240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='like_number',
        ),
        migrations.AlterField(
            model_name='report',
            name='reason',
            field=models.CharField(choices=[('not related to programing', 'not related to programing'), ('insulting', 'insulting'), ('sexual content', 'sexual content'), ('wrong answer', 'wrong answer'), ('inappropriate', 'inappropriate'), ('other', 'other')], default='publish', max_length=35),
        ),
    ]
