# Generated by Django 3.1.4 on 2021-01-03 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20210101_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questioncomment',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.question'),
        ),
    ]
