# Generated by Django 3.1.4 on 2021-01-07 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_questionviews'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ('-created_date',)},
        ),
    ]
