# Generated by Django 3.1.4 on 2021-01-10 12:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0017_auto_20210107_2042'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ('-created_date',), 'verbose_name': 'سوال'},
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('question liked', 'question likedd'), ('answer liked', 'answer liked'), ('question reported', 'question reported'), ('answer reported', 'answer reported'), ('comment reported', 'comment reported'), ('question answered', 'question answered'), ('question commented', 'question commented')], default='', max_length=35)),
                ('read', models.BooleanField(default=False)),
                ('body', models.CharField(blank=True, default='', max_length=500)),
                ('created_date', models.DateField(auto_now=True)),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
