# Generated by Django 3.1.4 on 2021-01-12 11:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20210112_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='view',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)]),
        ),
    ]
