# Generated by Django 3.1.4 on 2020-12-07 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20201204_1912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='answer_id',
        ),
        migrations.RemoveField(
            model_name='report',
            name='question_id',
        ),
        migrations.RemoveField(
            model_name='report',
            name='reported_profile',
        ),
        migrations.RemoveField(
            model_name='report',
            name='reprted_date',
        ),
        migrations.RemoveField(
            model_name='report',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='clubuser',
            name='gender',
            field=models.CharField(choices=[('male', 'آقا'), ('woman', 'خانم')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='slug',
            field=models.SlugField(blank=True, default='', null=True),
        ),
    ]
