# Generated by Django 3.1.4 on 2020-12-07 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20201207_1345'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='category',
            new_name='interest',
        ),
        migrations.AlterField(
            model_name='clubuser',
            name='gender',
            field=models.CharField(choices=[('woman', 'خانم'), ('male', 'آقا')], max_length=10, null=True),
        ),
    ]
