# Generated by Django 3.1.4 on 2021-01-13 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_auto_20210113_2145'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='report',
            name='duplicate_report',
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.UniqueConstraint(fields=('reporter', 'content_type', 'object_id'), name='duplicate_report'),
        ),
    ]
