# Generated by Django 3.1.4 on 2020-12-11 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubuser', '0001_initial'),
        ('blog', '0025_remove_clubuser_interest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubuser.clubuser'),
        ),
        migrations.AlterField(
            model_name='question',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubuser.clubuser'),
        ),
        migrations.DeleteModel(
            name='ClubUser',
        ),
    ]
