# Generated by Django 3.1.4 on 2020-12-13 16:16

from django.db import migrations, models
import django.db.models.deletion
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_auto_20201212_1827'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=56)),
                ('slug', models.SlugField(blank=True, default='', null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='question',
            name='body',
            field=djrichtextfield.models.RichTextField(),
        ),
        migrations.RemoveField(
            model_name='question',
            name='interest',
        ),
        migrations.AddField(
            model_name='question',
            name='interest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.category'),
        ),
        migrations.AddField(
            model_name='question',
            name='tag',
            field=models.ManyToManyField(to='blog.Tag'),
        ),
    ]
