# Generated by Django 3.1.4 on 2021-01-16 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0030_auto_20210116_0736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.TextField(max_length=255),
        ),
    ]
