# Generated by Django 3.1.4 on 2020-12-14 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0030_auto_20201214_1448'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='interest',
            new_name='category',
        ),
    ]
