# Generated by Django 3.1.4 on 2020-12-14 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0031_auto_20201214_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='tag',
            field=models.ManyToManyField(null=True, to='blog.Tag'),
        ),
    ]
