# Generated by Django 3.1.4 on 2021-01-21 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0032_contactus'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='valid_answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.answer'),
        ),
    ]
