# Generated by Django 3.1.4 on 2020-12-14 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0033_auto_20201214_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='status',
            field=models.CharField(choices=[('draft', 'draft'), ('publish', 'publish')], default='publish', max_length=15),
        ),
    ]
