# Generated by Django 3.1.4 on 2021-01-21 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0033_question_valid_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(blank=True, choices=[('question liked', 'question likedd'), ('answer liked', 'answer liked'), ('action reported', 'action reported'), ('question answered', 'question answered'), ('question commented', 'question commented'), ('answer validated', 'answer validated')], default='', max_length=35),
        ),
    ]
