# Generated by Django 3.1.4 on 2020-12-11 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0025_remove_clubuser_interest'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=15)),
                ('lname', models.CharField(max_length=15)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('email', models.CharField(max_length=40, unique=True)),
                ('gender', models.CharField(choices=[('woman', 'خانم'), ('male', 'آقا')], max_length=10, null=True)),
                ('sign_up_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('profile_image', models.ImageField(blank=True, default='01.png', null=True, upload_to='')),
                ('interest', models.ManyToManyField(to='blog.Category')),
            ],
        ),
    ]
