# Generated by Django 3.1.4 on 2021-01-21 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0032_contactus'),
        ('clubuser', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clubuser',
            name='interest',
        ),
        migrations.AddField(
            model_name='clubuser',
            name='interest',
            field=models.ManyToManyField(blank=True, to='blog.Category'),
        ),
    ]
