# Generated by Django 3.1.4 on 2021-01-21 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubuser', '0002_auto_20210121_1102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clubuser',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='clubuser',
            name='github',
        ),
        migrations.RemoveField(
            model_name='clubuser',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='clubuser',
            name='twitter',
        ),
        migrations.RemoveField(
            model_name='clubuser',
            name='website',
        ),
    ]
