# Generated by Django 3.1.4 on 2020-12-21 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubuser', '0003_auto_20201218_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubuser',
            name='profile_image',
            field=models.ImageField(blank=True, default='01.png', null=True, upload_to='clubuser/static/profiles'),
        ),
    ]
