# Generated by Django 3.1.4 on 2020-12-21 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubuser', '0004_auto_20201221_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubuser',
            name='profile_image',
            field=models.ImageField(blank=True, default='default.jpeg', null=True, upload_to='profile_pics'),
        ),
    ]
