# Generated by Django 3.1.4 on 2021-01-21 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubuser', '0004_auto_20210121_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubuser',
            name='website',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
