# Generated by Django 3.1.4 on 2020-12-14 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubuser', '0005_auto_20201214_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubuser',
            name='gender',
            field=models.CharField(choices=[('male', 'آقا'), ('woman', 'خانم')], max_length=10, null=True),
        ),
    ]
