# Generated by Django 3.1.4 on 2021-01-21 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubuser', '0005_auto_20210121_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubuser',
            name='facebook',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clubuser',
            name='github',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clubuser',
            name='instagram',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clubuser',
            name='twitter',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
